#Previous deploy.yml - The working one in Production:\
name: Deploy to Firebase (Dev & Prod)
on:
  push:
    branches:
      - main # Trigger on pushes to main (for PROD)

# Use an environment variable to set the correct Firebase Project ID
env:
     FIREBASE_PROJECT_ID: 'manuelmata-dev'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
     contents: 'read'

    steps:

     - name: Checkout Repository
       uses: actions/checkout@v4
    
     - name: Authenticate to Google Cloud
       uses: 'google-github-actions/auth@v2'
       with:
            # Conditionally select the correct service account key based on the branch
        credentials_json: ${{ secrets.GCP_SA_KEY }}


# --- All build steps remain the same ---

     # - name: Setup Flutter
     #   uses: subosito/flutter-action@v2
     #   with:
     #    channel: 'stable'
    
     # - name: Install Flutter Dependencies
     #   run: flutter pub get


     # - name: Build Web App
     #   run: flutter build web --release

     - name: Setup Node.js
       uses: actions/setup-node@v4
       with:
         node-version: '22'

     - name: Install Function Dependencies & Build
       run: | 
         cd functions
         npm ci npm run build
     - name: Install Firebase CLI
       run: npm install -g firebase-tools


# --- This deploy step now uses the dynamic project ID and debug flag---

     - name: Deploy to Firebase
       run: firebase deploy --only hosting,functions --project ${{ env.FIREBASE_PROJECT_ID }} --force --debug
